spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jobpulse}
    username: ${SPRING_DATASOURCE_USERNAME:jobpulse}
    password: ${SPRING_DATASOURCE_PASSWORD:jobpulse}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
