package com.harshit.demo.controller;

import org.hibernate.SessionFactory;
import org.hibernate.engine.jdbc.dialect.spi.DialectResolutionInfo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

/**
 * Controller to show Hibernate Dialect and Database Information
 * 
 * Access via: http://localhost:8080/api/hibernate/info
 */
@RestController
@RequestMapping("/api/hibernate")
public class HibernateInfoController {
    
    @Autowired
    private EntityManagerFactory entityManagerFactory;
    
    /**
     * Get Hibernate Dialect and Database Information
     * 
     * URL: GET /api/hibernate/info
     */
    @GetMapping("/info")
    public ResponseEntity<Map<String, Object>> getHibernateInfo() {
        Map<String, Object> info = new HashMap<>();
        
        try {
            EntityManager em = entityManagerFactory.createEntityManager();
            SessionFactory sessionFactory = em.getEntityManagerFactory()
                    .unwrap(org.hibernate.SessionFactory.class);
            
            // Get Dialect Information
            org.hibernate.dialect.Dialect dialect = sessionFactory.getSessionFactoryOptions()
                    .getJdbcServices()
                    .getDialect();
            
            info.put("hibernateDialect", dialect.getClass().getName());
            info.put("dialectName", dialect.getClass().getSimpleName());
            info.put("databaseName", "H2 Database");
            info.put("databaseVersion", "In-Memory");
            
            // Get Connection Info
            Properties properties = entityManagerFactory.getProperties();
            info.put("jdbcUrl", properties.get("javax.persistence.jdbc.url"));
            info.put("jdbcDriver", properties.get("javax.persistence.jdbc.driver"));
            info.put("jdbcUsername", properties.get("javax.persistence.jdbc.user"));
            
            // SQL Logging Status
            info.put("showSql", properties.get("hibernate.show_sql"));
            info.put("formatSql", properties.get("hibernate.format_sql"));
            
            // Hibernate Version
            String hibernateVersion = org.hibernate.Version.getVersionString();
            info.put("hibernateVersion", hibernateVersion);
            
            em.close();
            
            System.out.println("\n=========================================");
            System.out.println("📊 HIBERNATE DIALECT INFORMATION");
            System.out.println("=========================================");
            System.out.println("Dialect: " + dialect.getClass().getName());
            System.out.println("Database: H2 (In-Memory)");
            System.out.println("Hibernate Version: " + hibernateVersion);
            System.out.println("SQL Logging: Enabled");
            System.out.println("=========================================\n");
            
        } catch (Exception e) {
            info.put("error", "Could not retrieve Hibernate info: " + e.getMessage());
            e.printStackTrace();
        }
        
        return ResponseEntity.ok(info);
    }
    
    /**
     * Get SQL Query Examples
     * 
     * URL: GET /api/hibernate/sql-examples
     */
    @GetMapping("/sql-examples")
    public ResponseEntity<Map<String, Object>> getSqlExamples() {
        Map<String, Object> examples = new HashMap<>();
        
        examples.put("dialect", "H2Dialect");
        examples.put("sqlQueries", new String[]{
            "SELECT * FROM users",
            "SELECT u FROM User u",
            "SELECT u FROM User u WHERE u.email = :email",
            "SELECT u FROM User u ORDER BY u.id",
            "SELECT COUNT(u) FROM User u"
        });
        
        examples.put("note", "Check console for actual SQL queries generated by Hibernate");
        examples.put("consoleLogging", "SQL queries are logged in console with DEBUG level");
        examples.put("h2Console", "http://localhost:8080/h2-console - Run SQL directly");
        
        return ResponseEntity.ok(examples);
    }
}










