package com.harshit.hibernate.basic.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.Date;

/**
 * User Entity - Basic Hibernate/JPA Entity Example
 * 
 * ====================================================================================
 * INTERVIEW QUESTION: Explain JPA entity annotations and their purpose.
 * ====================================================================================
 * 
 * DETAILED ANSWER:
 * 
 * JPA entities are Java classes that represent database tables. They use annotations
 * to map Java objects to relational database structures. Let me explain each annotation:
 * 
 * @Entity:
 * - Marks this class as a JPA entity
 * - Tells JPA that this class should be mapped to a database table
 * - The table name defaults to the class name (User -> users, camelCase to snake_case)
 * - Entity classes must have a no-argument constructor
 * - Entity classes should not be final (Hibernate uses proxies)
 * 
 * @Table:
 * - Specifies the database table name
 * - Optional - if omitted, table name is derived from entity name
 * - Can specify schema, catalog, indexes, unique constraints
 * - Example: @Table(name = "users", schema = "public")
 * 
 * @Id:
 * - Marks a field as the primary key
 * - Each entity must have exactly one @Id field
 * - Can be on a field or getter method
 * - Primary key uniquely identifies each row in the table
 * 
 * @GeneratedValue:
 * - Specifies how the primary key value is generated
 * - Strategies:
 *   * IDENTITY: Database auto-increment (MySQL AUTO_INCREMENT, PostgreSQL SERIAL)
 *   * SEQUENCE: Uses database sequence (Oracle, PostgreSQL)
 *   * TABLE: Uses a separate table to generate IDs
 *   * AUTO: Let JPA provider choose (usually IDENTITY or SEQUENCE)
 * - IDENTITY is most common and works with most databases
 * 
 * @Column:
 * - Maps a field to a database column
 * - Optional - if omitted, column name is derived from field name
 * - Attributes:
 *   * name: Column name in database
 *   * nullable: Can the column be NULL?
 *   * unique: Is the column unique?
 *   * length: Maximum length (for String)
 *   * precision/scale: For BigDecimal
 *   * insertable/updatable: Can this column be inserted/updated?
 * 
 * @Temporal:
 * - Specifies how Date/Calendar should be persisted
 * - Types:
 *   * DATE: Only date (YYYY-MM-DD)
 *   * TIME: Only time (HH:MM:SS)
 *   * TIMESTAMP: Date and time (YYYY-MM-DD HH:MM:SS)
 * - Required for Date/Calendar fields in JPA 2.1 and earlier
 * - Optional in JPA 2.2+ (uses TIMESTAMP by default)
 * 
 * @Enumerated:
 * - Maps Java enum to database column
 * - Strategies:
 *   * ORDINAL: Stores enum index (0, 1, 2...) - not recommended (breaks if enum order changes)
 *   * STRING: Stores enum name ("ACTIVE", "INACTIVE") - recommended
 * 
 * @PrePersist and @PreUpdate:
 * - Lifecycle callbacks - methods called automatically by JPA
 * - @PrePersist: Called before entity is persisted (INSERT)
 * - @PreUpdate: Called before entity is updated (UPDATE)
 * - Useful for setting timestamps, validation, etc.
 * 
 * ====================================================================================
 * LOMBOK ANNOTATIONS (Reduces Boilerplate):
 * ====================================================================================
 * 
 * @Data:
 * - Generates getters, setters, toString(), equals(), hashCode()
 * - Equivalent to @Getter + @Setter + @ToString + @EqualsAndHashCode
 * 
 * @NoArgsConstructor:
 * - Generates no-argument constructor
 * - Required by JPA (entities must have no-arg constructor)
 * 
 * @AllArgsConstructor:
 * - Generates constructor with all fields
 * - Useful for creating entities with all values
 * 
 * ====================================================================================
 * REAL-WORLD SCENARIO:
 * ====================================================================================
 * 
 * In a user management system, this entity would represent a user account:
 * - Each user has a unique ID (primary key)
 * - Username and email must be unique
 * - Created/updated timestamps track when user was created/modified
 * - Status enum represents user account state (active, inactive, suspended)
 * 
 * This entity would be used in:
 * - User registration (persist new user)
 * - User login (find by username/email)
 * - User profile updates (update existing user)
 * - User management (activate/deactivate users)
 */
@Entity
@Table(name = "users", 
       uniqueConstraints = {
           @UniqueConstraint(columnNames = "username"),
           @UniqueConstraint(columnNames = "email")
       })
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User {
    
    /**
     * Primary Key
     * - Auto-generated by database (IDENTITY strategy)
     * - Unique identifier for each user
     * - Cannot be null
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * Username
     * - Must be unique (enforced by unique constraint)
     * - Cannot be null
     * - Maximum 50 characters
     */
    @Column(name = "username", nullable = false, unique = true, length = 50)
    private String username;
    
    /**
     * Email Address
     * - Must be unique (enforced by unique constraint)
     * - Cannot be null
     * - Used for login and communication
     */
    @Column(name = "email", nullable = false, unique = true)
    private String email;
    
    /**
     * First Name
     * - Optional field (can be null)
     * - User's first name
     */
    @Column(name = "first_name")
    private String firstName;
    
    /**
     * Last Name
     * - Optional field (can be null)
     * - User's last name
     */
    @Column(name = "last_name")
    private String lastName;
    
    /**
     * Age
     * - Optional field (can be null)
     * - User's age in years
     */
    @Column(name = "age")
    private Integer age;
    
    /**
     * Created Timestamp
     * - Automatically set when user is first created
     * - Set by @PrePersist callback
     * - Stores both date and time
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, updatable = false)
    private Date createdAt;
    
    /**
     * Updated Timestamp
     * - Automatically updated when user is modified
     * - Set by @PreUpdate callback
     * - Tracks last modification time
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at")
    private Date updatedAt;
    
    /**
     * User Status
     * - Enum representing user account state
     * - Stored as STRING in database ("ACTIVE", "INACTIVE", "SUSPENDED")
     * - More readable and maintainable than storing numbers
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private UserStatus status = UserStatus.ACTIVE;
    
    /**
     * Lifecycle Callback: Before Persist
     * - Automatically called by JPA before INSERT
     * - Sets createdAt and updatedAt timestamps
     * - Ensures timestamps are always set correctly
     */
    @PrePersist
    protected void onCreate() {
        Date now = new Date();
        this.createdAt = now;
        this.updatedAt = now;
    }
    
    /**
     * Lifecycle Callback: Before Update
     * - Automatically called by JPA before UPDATE
     * - Updates the updatedAt timestamp
     * - Tracks when entity was last modified
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = new Date();
    }
    
    /**
     * Convenience Constructor
     * - Creates user with required fields
     * - Sets default status to ACTIVE
     * - Timestamps will be set by @PrePersist
     */
    public User(String username, String email) {
        this.username = username;
        this.email = email;
        this.status = UserStatus.ACTIVE;
    }
}

/**
 * User Status Enumeration
 * 
 * Represents the possible states of a user account:
 * - ACTIVE: User can log in and use the system
 * - INACTIVE: User account is disabled but not deleted
 * - SUSPENDED: User account is temporarily suspended
 */
enum UserStatus {
    ACTIVE,      // User account is active and can be used
    INACTIVE,    // User account is inactive (disabled)
    SUSPENDED    // User account is suspended (temporarily disabled)
}

